services:
  - type: web
    name: slack-cumples
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GOOGLE_SHEET_ID
        value: TU_ID_DE_SHEET
      - key: SLACK_BOT_TOKEN
        value: TU_TOKEN
      - key: SLACK_SIGNING_SECRET
        value: TU_SECRET
      - key: PORT
        value: 10000
