services:
  - type: web
    name: slack-cumples
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
